[package]
name = "florui-paint"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[lib]
name = "florui_paint"

[dependencies]
florui-layout = { path = "../florui-layout" }
florui-style = { path = "../florui-style" }
florui-text = { path = "../florui-text" }
png = "0.17"
skrifa = "0.44"
tiny-skia = "0.11"

[dev-dependencies]
florui = { path = "../florui" }
taffy = "0.14"
criterion = "0.5"

[[bench]]
name = "paint"
harness = false
