[package]
name = "florui-paint"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[lib]
name = "florui_paint"

[dependencies]
florui-layout = { path = "../florui-layout" }
florui-style = { path = "../florui-style" }
image = { version = "0.25", default-features = false, features = ["png"] }

[dev-dependencies]
florui = { path = "../florui" }
taffy = "0.14"
