[workspace]
resolver = "3"
members = [
    "crates/florui-devtools",
    "crates/florui-cli",
    "crates/florui-primitives",
    "crates/florui-macros",
    "crates/florui",
    "crates/florui-conformance",
    "crates/florui-build",
    "crates/florui-style",
    "crates/florui-layout",
    "examples/florui-example-app",
]

[workspace.package]
edition = "2024"
rust-version = "1.94"
