[package]
license.workspace = true
name = "florui-devtools"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[lib]
name = "florui_devtools"

[dependencies]
florui = { path = "../florui" }
florui-style = { path = "../florui-style" }
florui-layout = { path = "../florui-layout" }
florui-paint = { path = "../florui-paint" }
florui-platform = { path = "../florui-platform" }
taffy = "0.14"
winit = "0.30.13"
softbuffer = "0.4.8"
notify = "8.2.0"
image = { version = "0.25.10", default-features = false, features = ["png"] }
wgpu = "29.0.4"
egui = "0.35.0"
egui-winit = "0.35.0"
egui-wgpu = { version = "0.35.0", features = ["winit"] }
pollster = "1.0.1"
