[package]
license.workspace = true
name = "florui-devtools"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[lib]
name = "florui_devtools"

[dependencies]
winit = "0.30.13"
softbuffer = "0.4.8"
notify = "8.2.0"
image = { version = "0.25.10", default-features = false, features = ["png"] }
