[package]
name = "florui-style"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[lib]
name = "florui_style"

[dependencies]
florui = { path = "../florui" }
app_units = "0.7"
atomic_refcell = "0.1"
cssparser = "0.35"
euclid = "0.22"
selectors = "0.32"
servo_arc = "0.4"
stylo = "0.8"
stylo_atoms = "0.8"
stylo_config = "0.8"
stylo_dom = "0.8"
url = "2"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "style"
harness = false
