[package]
name = "florui-view-syntax"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
florui-primitives = { path = "../florui-primitives" }
syn = { version = "2", features = ["full", "extra-traits"] }
proc-macro2 = { version = "1", features = ["span-locations"] }

[dev-dependencies]
quote = "1"
