[package]
name = "florui-fmt"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
florui-view-syntax = { path = "../florui-view-syntax" }
syn = { version = "2", features = ["full", "extra-traits", "visit"] }
proc-macro2 = { version = "1", features = ["span-locations"] }

[dev-dependencies]
tempfile = "3"
