[package]
name = "florui-example-app"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[lib]
name = "florui_example_app"

[[bin]]
name = "florui-example-app"
path = "src/main.rs"

[dependencies]
florui = { path = "../../crates/florui" }
florui-devtools = { path = "../../crates/florui-devtools" }

[build-dependencies]
florui-build = { path = "../../crates/florui-build" }
